name: all_covid_resources
description: A collection of all COVID related resources and websites.

publish_to: 'none'

version: 1.2.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.0.2
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.0
  url_launcher: ^6.0.3
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/